source :rubygems

# Dependencies are generated using a strict version,
# Don't forget to edit the dependency versions when upgrading.

merb_gems_version      = "<%= merb_gems_version %>"
merb_auth_gems_version = "<%= merb_auth_gems_version %>"
dm_gems_version        = "<%= dm_gems_version %>"
do_gems_version        = "<%= do_gems_version %>"

# If you did disable json for Merb, comment out this line.
# Don't use json gem version lower than 1.1.7! Older version have a security bug

gem "json_pure", ">= 1.1.7", :require => "json"

# For more information about each component,
# please read https://github.com/merb/merb/wiki/Core-Modules

gem "merb-core",                merb_gems_version
gem "merb-action-args",         merb_gems_version
gem "merb-assets",              merb_gems_version
gem "merb-helpers",             merb_gems_version
gem "merb-mailer",              merb_gems_version
gem "merb-slices",              merb_gems_version
gem "merb-param-protection",    merb_gems_version
gem "merb-exceptions",          merb_gems_version
gem "merb-gen",                 merb_gems_version

gem("merb-cache", merb_gems_version) do
  Merb::Cache.setup do
    register(Merb::Cache::FileStore) unless Merb.cache
  end
end

gem "merb-auth-core",           merb_auth_gems_version
gem "merb-auth-more",           merb_auth_gems_version
gem "merb-auth-slice-password", merb_auth_gems_version

# Change to server of your choice
gem "thin"

# DataMapper gems: http://www.datamapper.org
gem "dm-core",                  dm_gems_version
gem "dm-sqlite-adapter",        dm_gems_version # change as needed
gem "dm-aggregates",            dm_gems_version
gem "dm-migrations",            dm_gems_version
gem "dm-timestamps",            dm_gems_version
gem "dm-types",                 dm_gems_version
gem "dm-validations",           dm_gems_version
gem "dm-serializer",            dm_gems_version
gem "dm-constraints",           dm_gems_version

<%= gems_for_orm(orm) %>
<%= gems_for_template_engine(template_engine) %>
<%= gems_for_testing_framework(testing_framework) %>

